{"uuid": "6e3d6eb6-5b57-449e-b1e1-71a27c15e57a", "children": ["e09a02bb-cf23-4c3d-826f-6e476e8dad6a"], "befores": [{"name": "api_client", "status": "broken", "statusDetails": {"message": "KeyError: 'api'\n", "trace": "  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\user\\Desktop\\skypro\\final_proj\\pytest_ui_api_template\\test\\conftest.py\", line 23, in api_client\n    url = ConfigProvider().getint(\"api\", \"base_url\")\n  File \"C:\\Users\\user\\Desktop\\skypro\\final_proj\\pytest_ui_api_template\\conficuration\\configprovider.py\", line 13, in getint\n    return self.config[section].getint(prop)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\configparser.py\", line 998, in __getitem__\n    raise KeyError(key)\n"}, "start": 1737632926294, "stop": 1737632926301}], "start": 1737632926294, "stop": 1737632926421}